image: docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:dind
    alias: docker
    command: ["--tls=false"]

stages:
  - build

build:
  stage: build
  script:
    - docker info
