default:
  image: docker:dind
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false"]
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_USER/javatest:latest .
    - docker push $CI_REGISTRY_USER/javatest:latest

test:
  stage: test
  script:
    - docker pull $CI_REGISTRY_USER/javatest:latest
    - docker run --rm $CI_REGISTRY_USER/javatest:latest

